# Generated by Django 3.2.7 on 2021-09-23 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(max_length=255, unique=True, verbose_name='discount code')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_discount_codes', to='store.store')),
            ],
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
