# Generated by Django 3.2.7 on 2021-09-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_client_time_zone_client_time_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='time_zone',
            new_name='timezone',
        ),
    ]
