# Generated by Django 3.2.7 on 2021-09-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210923_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='operator_group',
            field=models.ManyToManyField(to='account.OperatorGroup'),
        ),
    ]
