# Generated by Django 3.2.7 on 2021-09-23 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='payload',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('[^\\w\\s{}$%_\\/~@.#$%^&()!?-]', '')]),
        ),
    ]
