# Generated by Django 3.2.7 on 2021-09-25 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210925_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('in-progress', 'In Progress'), ('finish', 'Finish')], default='created', max_length=12)),
                ('schedule_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_schedule', to='chat.chat')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
